Repository binsync/binsync, pull requests merged in 2021-08, with the labels that each got.

#44 Added type syncing for struct members
  plugins/ida_binsync/ida_binsync/compat.py
  plugins/ida_binsync/ida_binsync/controller.py
Labels: enhancement, ida

#45 fixed comment syncing
  plugins/ida_binsync/ida_binsync/controller.py
  plugins/ida_binsync/ida_binsync/hooks.py
  plugins/ida_binsync/ida_binsync/ui/info_tables/func_info_table.py
  plugins/ida_binsync/ida_binsync/ui/info_tables/struct_info_table.py
  plugins/ida_binsync/ida_binsync/ui/info_tables/user_info_table.py
Labels: bug, ida

#55 Added better binja install instructions
  README.md
  plugins/binja_binsync/plugin.json
  scripts/install.sh
Labels: binary ninja, enhancement

#58 Fix checkout issues with this one easy trick.
  binsync/client.py
Labels: bug, core

#59 WIP: Binja Modern UI Support
  plugins/binja_binsync/binja_binsync.py
  plugins/binja_binsync/config_dialog.py
  plugins/binja_binsync/control_panel.py
  plugins/binja_binsync/controller.py
  plugins/binja_binsync/status_table.py
  plugins/binja_binsync/ui/__init__.py
  plugins/binja_binsync/ui/config_dialog.py
  plugins/binja_binsync/ui/info_panel.py
  plugins/binja_binsync/ui/info_tables/__init__.py
  plugins/binja_binsync/ui/info_tables/autosync_info_table.py
  plugins/binja_binsync/ui/info_tables/cur_func_info_table.py
  plugins/binja_binsync/ui/info_tables/func_info_table.py
  plugins/binja_binsync/ui/info_tables/struct_info_table.py
  plugins/binja_binsync/ui/info_tables/user_info_table.py
  plugins/binja_binsync/ui/ui_tools.py
Labels: binary ninja, refactor
